env:
  matrix:
  - VERSION=0.1.0
  global:
    secure: SBL+LuX5FI93o7lFMAz+2yA37ZXvhm4R1vN0O7YIYvGdCnQulQYZGmtxT318ifl5CzUiWrxWYBqEUYKsWq03l2CEffXeSJ1EAWsxj+pRdFb6E88MGgQd87doEwweo2JMqrxV3sv0vnVyGtZPtn1clsSu87Kvd71Ble668xlm3mg6WINIUWFhjqsG9ZusghYdX5xj98w5USmhT+l2nvsydg4Fx6KWJeXX2p8nc6UATVBlcjaM5OhiMNN9Cy2cB/eT8F1VmvWaTmVR0+UwfbxM67MDxng4nNfzDQW+m2Osm2CvUcpRftUDssRN5uH3iPIeBxxXpzYBZh1TN2eFGEA04cyD6E+L+5FUveBjrw1Ib03VtgprPQYeu4fd/6aSuS0j2aI+i2cMNyocqnsSQSwz6lt/p8dDEOGrmyVFxURSF0hopwWUSfxL2oPZNgbDDejruimubWfqu9CmHDVQ9Djawcu48lxB2BmHbg8B2JXz2nQ+bw9pHR1mCMoYHbWNagC27ooPgB3nF4dKwWLG9JjCZIUSALBhwK7bf5IaJ1iIiXjqpu8uiJIDNwfzikt+jcr7kdS5mgo2pNSc+4W6sXlJxgJ/42i9ZqDFU7GjxnLH8Qa0OJhBxKEJsvjkMw+7XeGu4Q0BABYpb2ea05ri8PLsg/IiHcMzZ2i5pGshceq0C9A=

services:
- docker

script:
- docker build --build-arg VERSION="${VERSION}" -t temp-build .
- docker run --rm temp-build --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
